ez_recommendation.content_type.get_content:
    path: /ez_recommendation/v1/content/{idList}
    defaults:
        _controller: 'EzSystems\EzRecommendationClientBundle\Controller\ContentController::getContentAction'
    methods: [GET]

ez_recommendation.export.download:
    path: /ez_recommendation/v1/exportDownload/{filePath}
    defaults:
        _controller: 'EzSystems\EzRecommendationClientBundle\Controller\ExportController::downloadAction'
    requirements:
        filePath: '[a-zA-Z0-9\_\-\/]+'
