services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzRecommendationClientBundle\Command\:
        resource: '../../../../src/bundle/Command/*'

    EzSystems\EzRecommendationClientBundle\Command\ExportCommand:
        tags:
            - { name: console.command, command: ezrecommendation:export:run }
            - { name: monolog.logger, channel: ezrecommendation }

    EzSystems\EzRecommendationClientBundle\Command\UserAttributesUpdateCommand:
        tags:
            - { name: console.command, command: ezrecommendation:user:update }
            - { name: monolog.logger, channel: ezrecommendation }
