services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\Bundle\PersonalizationClient\Command\ExportCommand:
        tags:
            - { name: console.command }
            - { name: monolog.logger, channel: ibexa-recommendation }

    EzSystems\EzRecommendationClientBundle\Command\UserAttributesUpdateCommand:
        tags:
            - { name: console.command }
            - { name: monolog.logger, channel: ibexa-recommendation }
