services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\PersonalizationClient\Content\DataResolver: ~

    Ibexa\PersonalizationClient\Content\DataResolverInterface:
        '@Ibexa\PersonalizationClient\Content\DataResolver'
