services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    EzSystems\EzRecommendationClientBundle\ParamConverter\:
        resource: '../../../../src/bundle/ParamConverter/*'

    EzSystems\EzRecommendationClientBundle\ParamConverter\ListParamConverter:
        tags:
            - { name: request.param_converter, priority: -2, converter: list_converter }
