services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzRecommendationClient\Exporter\Exporter:
        tags:
            - { name: monolog.logger, channel: ibexa-recommendation }
        arguments:
            $notificationService: '@EzSystems\EzRecommendationClient\Service\ExportNotificationService'

    EzSystems\EzRecommendationClient\Exporter\ExporterInterface:
        '@EzSystems\EzRecommendationClient\Exporter\Exporter'
