services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\PersonalizationClient\Export\Input\CommandInputResolver: ~

    Ibexa\PersonalizationClient\Export\Input\CommandInputResolverInterface:
        '@Ibexa\PersonalizationClient\Export\Input\CommandInputResolver'
