services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\PersonalizationClient\Generator\SecureUniqueStringGenerator: ~

    Ibexa\PersonalizationClient\Generator\UniqueStringGeneratorInterface:
        '@Ibexa\PersonalizationClient\Generator\SecureUniqueStringGenerator'

    EzSystems\EzRecommendationClient\Generator\ContentListElementGenerator: ~
