services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\PersonalizationClient\Generator\UniqueStringGenerator: ~

    Ibexa\PersonalizationClient\Generator\UniqueStringGeneratorInterface:
        '@Ibexa\PersonalizationClient\Generator\UniqueStringGenerator'

    EzSystems\EzRecommendationClient\Generator\ContentListElementGenerator: ~
