services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\PersonalizationClient\Generator\Password\RandomPasswordGenerator: ~

    Ibexa\PersonalizationClient\Generator\Password\PasswordGeneratorInterface:
        '@Ibexa\PersonalizationClient\Generator\Password\RandomPasswordGenerator'

    EzSystems\EzRecommendationClient\Generator\ContentListElementGenerator: ~
