services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\PersonalizationClient\QueryType\ContentDataSourceQueryType:
        tags:
            - { name: ezplatform.query_type }
