services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzRecommendationClient\Response\ItemListResponseRenderer:
        tags:
            - { name: ibexa.personalization.rest.response_type, type: http }

    EzSystems\EzRecommendationClient\Response\ResponseRendererInterface:
        '@EzSystems\EzRecommendationClient\Response\ItemListResponseRenderer'
