services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\Personalization\Storage\ContentDataSource:
        arguments:
            $queryType: '@Ibexa\Personalization\QueryType\ContentDataSourceQueryType'
