services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Ibexa\Contracts\Personalization\Storage\DataSourceInterface:
            tags:
                - { name: ibexa.personalization.data_source }
