services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\PersonalizationClient\Storage\ContentDataSource:
        arguments:
            $queryType: '@Ibexa\PersonalizationClient\QueryType\ContentDataSourceQueryType'
