services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        EzSystems\EzRecommendationClient\Strategy\Storage\GroupItemStrategyInterface:
            tags:
                - { name: ibexa.personalization.group_item.strategy }

    EzSystems\EzRecommendationClient\Strategy\Storage\GroupByItemTypeAndLanguageStrategy: ~

    EzSystems\EzRecommendationClient\Strategy\Storage\ItemGroupListStrategy:
        arguments:
            $strategies: !tagged_iterator { tag: ibexa.personalization.group_item.strategy, default_index_method: getIndex }

    EzSystems\EzRecommendationClient\Strategy\Storage\ItemGroupListStrategyInterface:
        '@EzSystems\EzRecommendationClient\Strategy\Storage\ItemGroupListStrategy'
